// Code generated by "stringer -type=TokenType ./lexer"; DO NOT EDIT.

package lexer

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Identifier-0]
	_ = x[Println-1]
	_ = x[Print-2]
	_ = x[Var-3]
	_ = x[StringType-4]
	_ = x[NumberType-5]
	_ = x[For-6]
	_ = x[If-7]
	_ = x[Else-8]
	_ = x[Integer-9]
	_ = x[Float-10]
	_ = x[Percent-11]
	_ = x[Dash-12]
	_ = x[Plus-13]
	_ = x[PlusEquals-14]
	_ = x[DoublePlus-15]
	_ = x[Mult-16]
	_ = x[Div-17]
	_ = x[Equals-18]
	_ = x[String-19]
	_ = x[LeftCurlyBrace-20]
	_ = x[RightCurlyBrace-21]
	_ = x[LeftParen-22]
	_ = x[RightParen-23]
	_ = x[LessThanEquals-24]
	_ = x[LessThan-25]
	_ = x[GreaterThanEquals-26]
	_ = x[GreaterThan-27]
	_ = x[DoubleEquals-28]
	_ = x[Not-29]
	_ = x[NotEquals-30]
	_ = x[Period-31]
	_ = x[Newline-32]
	_ = x[Hash-33]
	_ = x[EndTokenList-34]
}

const _TokenType_name = "IdentifierPrintlnPrintVarStringTypeNumberTypeForIfElseIntegerFloatPercentDashPlusPlusEqualsDoublePlusMultDivEqualsStringLeftCurlyBraceRightCurlyBraceLeftParenRightParenLessThanEqualsLessThanGreaterThanEqualsGreaterThanDoubleEqualsNotNotEqualsPeriodNewlineHashEndTokenList"

var _TokenType_index = [...]uint16{0, 10, 17, 22, 25, 35, 45, 48, 50, 54, 61, 66, 73, 77, 81, 91, 101, 105, 108, 114, 120, 134, 149, 158, 168, 182, 190, 207, 218, 230, 233, 242, 248, 255, 259, 271}

func (i TokenType) String() string {
	if i < 0 || i >= TokenType(len(_TokenType_index)-1) {
		return "TokenType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _TokenType_name[_TokenType_index[i]:_TokenType_index[i+1]]
}
